version: '2'

services:
  web:
    build: 
      context: docker/images/apache
      args:
        SERVER_NAME: ikea
        DOCUMENT_ROOT: /var/www/html/public
    ports:
      - "4000:80"
    volumes:
      - .:/var/www/html
  db:
    image: sameersbn/mysql
    volumes:
      - /var/lib/mysql
    ports:
      - "5306:3306"
    environment:
      - DB_NAME=db_ikea
      - DB_USER=ikea_user
      - DB_PASS=passwd
      - DB_REMOTE_ROOT_NAME=root
      - DB_REMOTE_ROOT_PASS=9ok32Vuk
      - DB_REMOTE_ROOT_HOST=172.20.0.3
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"