version: '2'

services:
  web:
    build: 
      context: docker/images/apache
      args:
        SERVER_NAME: ikea
        DOCUMENT_ROOT: /var/www/html/public
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
  db:
    image: sameersbn/mysql
    volumes:
      - /var/lib/mysql
    ports:
      - "5306:3306"
    environment:
      - DB_NAME=db_ikea
      - DB_USER=ikea_user
      - DB_PASS=8Adec366bd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"